#!/bin/bash

set -e

WF_DIR=$1
if [ "x$1" = "x" ]; then
    echo "Please specify workflow directory" 1>&2
    exit 1
fi

cd $WF_DIR

if [ ! -e braindump.txt ]; then
    echo "braindump.txt was not found in this directory. Planner probably failed!" 1>&2
    exit 1
fi

STATUS=`pegasus-status --noqueue | tail -1 | sed 's/[:\(\)]/ /g'| awk '{print $5}'`
echo "STATUS=$STATUS"

pegasus-status --noqueue --rows \
  | sed 's/: /=/' \
  | sed 's/%DONE/PERCENT_DONE/' \
  | grep -v ^Summary

